// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motorcycle_WebShop.Data;

#nullable disable

namespace Motorcycle_WebShop.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231110113845_Added15ProductsToDatabase")]
    partial class Added15ProductsToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4bc6d9be - 018d - 4cd9 - acaa - d855942ee8d9",
                            Name = "Chief executive officer",
                            NormalizedName = "CHIEF EXECUTIVE OFFICER"
                        },
                        new
                        {
                            Id = "811bf54e-ec17-457f-917b-c432d1060070",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "edffea81-92bf-4400-84f3-047a9f72cbc7",
                            Name = "Support",
                            NormalizedName = "SUPPORT"
                        },
                        new
                        {
                            Id = "2cd04bd9-83ff-49a3-a1b7-e97a5e9896d9",
                            Name = "Secretary",
                            NormalizedName = "SECRETARY"
                        },
                        new
                        {
                            Id = "94a721f8-f477-40f7-aec2-057742da1c26",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Motorcycle_WebShop.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AvatarFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastKnownIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BillingFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillingLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillingPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BillingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShippingFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "When Yamaha launched the first MT Hyper Naked a decade ago the motorcycle world changed forever. With a clear focus on torque, agility and feel, the MT range has given riders the chance to experience the raw emotion and on-demand excitement that makes every Hyper Naked special.",
                            IsActive = true,
                            Price = 15199m,
                            Quantity = 14m,
                            Title = "YAMAHA MT-10"
                        },
                        new
                        {
                            Id = 2,
                            Description = "In 2015, the first Tracer 900 changed the Sport Touring class forever. With its torque-rich CP3 engine, sporty chassis and all-round versatility, it became the bike of choice for over 50,000 European riders who wanted an agile and exciting multi-role motorcycle with plenty of attitude. Perhaps no surprise then that it’s the best-selling bike of its class.",
                            IsActive = true,
                            Price = 16499m,
                            Quantity = 10m,
                            Title = "YAMAHA TRACER 9"
                        },
                        new
                        {
                            Id = 3,
                            Description = "R1 is the most focused and high-tech Supersport bike ever built by Yamaha, ever since the launch of the original model over 25 years ago. And just about everything on the latest R1 can directly trace its origins back to the racetrack, where Yamaha’s factory racing teams and test riders have been developing and testing the advanced technology that you can now see and experience on your R1. ",
                            IsActive = true,
                            Price = 17399m,
                            Quantity = 21m,
                            Title = "YAMAHA R1"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is the kind of motorcycle that you can enjoy in almost any kind of situation. It’s easy ergonomics are specially designed to give you an open and adaptable riding position that makes every ride more enjoyable. From narrow twisty backroads through to fast open corners or relaxed cruising through town, the XSR900 is ready for anything. ",
                            IsActive = true,
                            Price = 10199m,
                            Quantity = 13m,
                            Title = "YAMAHA XSR900"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The key to NIKEN GT’s outstanding handling performance is Yamaha’s LMW system. Featuring twin leaning front wheels, this innovative front end gives class leading cornering performance with enhanced feelings of stability – and it’s what makes this premium Sport Tourer one of the most capable machines in its category. ",
                            IsActive = true,
                            Price = 15999m,
                            Quantity = 11m,
                            Title = "YAMAHA NIKEN"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Now even more stylish and aggressively muscular, just a quick glance and you catch the burnished metal finishes that reflect the tradition of a hard-charging Café Racer. ",
                            IsActive = true,
                            Price = 13499m,
                            Quantity = 17m,
                            Title = "HONDA CB1000R"
                        },
                        new
                        {
                            Id = 7,
                            Description = "This is why we race. Why we’ve always raced, and it is feedback from HRC and our riders that’s produced the new CBR1000RR-R Fireblade. It’s got more mid-range power from intake and cylinder head upgrades, with revised gearbox ratios for incredible drive out of corners. ",
                            IsActive = true,
                            Price = 27899m,
                            Quantity = 13m,
                            Title = "HONDA CB1000RR"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Forget the expected. It’s time for a new generation to shake things up. Start with a brand-new engine producing incredible, class-leading power. Dial in a lightweight chassis honed for sports, tightly wrapped in head-turning streetfighter style and the new CB750 Hornet takes flight. Nothing else comes close. ",
                            IsActive = true,
                            Price = 27899m,
                            Quantity = 16m,
                            Title = "HONDA CB750 HORNET"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The Gold Wing Tour takes care of rider and pillion alike. With dynamic handling and engine response to satisfy any rider, the pillion can settle back into their luxurious and even more expansive space and enjoy the journey ahead. ",
                            IsActive = true,
                            Price = 37799m,
                            Quantity = 9m,
                            Title = "HONDA GL1800 GOLD WING"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The NT1100 offers everything you need in one motorcycle. It’s built agile for the demands of the city with light, easy handling and long-travel suspension. ",
                            IsActive = true,
                            Price = 15499m,
                            Quantity = 13m,
                            Title = "HONDA NT1100"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Turn heads as you take on your next adventure aboard a Kawasaki Vulcan 900 cruiser. Right off the showroom floor, the 903cc V-twin powered cruiser has all the style and attitude of a one-of-a-kind build. From the detailed paint to the exciting exhaust, the Vulcan 900 Series is an artful expression of individuality. ",
                            IsActive = true,
                            Price = 8999m,
                            Quantity = 15m,
                            Title = "KAWASAKI VULCAN 900"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The sport appeal of Kawasaki Ninja motorcycles goes well beyond the racetrack with the remarkably versatile Ninja 1000SX sportbike. Enjoy pure sporting thrill with superior power, two-up touring capability and advanced rider support electronics. A force to be reckoned with on the track and a machine built for weekend trips. ",
                            IsActive = true,
                            Price = 17549m,
                            Quantity = 11m,
                            Title = "KAWASAKI NINJA 1000SX"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The Ninja ZX™-10R supersport bike is built for those who rise to the challenge. Hailing from the proving grounds of the FIM WorldSBK Championship, the Ninja ZX-10R is the direct result of decades of world-class road racing innovation, carrying the Kawasaki Racing Team (KRT) to six consecutive championship titles. Push your limits aboard the Ninja ZX-10R. ",
                            IsActive = true,
                            Price = 17799m,
                            Quantity = 17m,
                            Title = "KAWASAKI NINJA ZX-10R"
                        },
                        new
                        {
                            Id = 14,
                            Description = " ",
                            IsActive = true,
                            Price = 9999m,
                            Quantity = 21m,
                            Title = "KAWASAKI Z900"
                        },
                        new
                        {
                            Id = 15,
                            Description = "The development of the Ninja H2R motorcycle goes beyond the boundaries of any other Kawasaki motorcycle. Born through the unprecedented collaboration between multiple divisions within the Kawasaki Heavy Industries, Ltd. (KHI) organization, the limited-production supercharged model represents the unbridled pinnacle of Kawasaki engineering, with astonishing acceleration and mind-bending top speed suitable only for the track. ",
                            IsActive = true,
                            Price = 62299m,
                            Quantity = 5m,
                            Title = "KAWASAKI NINJA H2R"
                        },
                        new
                        {
                            Id = 16,
                            Description = "At the pinnacle of the GSX-R family of ultra-high-performance motorcycles, the 2024 GSX-R1000R’s versatile engine provides class-leading power that is delivered smoothly and controllably across a broad rpm range. Like the original GSX-R1000, the 2024’s compact chassis delivers nimble handling with excellent suspension feel and braking control, ready to conquer a racetrack or cruise a country road.",
                            IsActive = true,
                            Price = 18499m,
                            Quantity = 13m,
                            Title = "SUZUKI GSX-R1000R"
                        },
                        new
                        {
                            Id = 17,
                            Description = "The Suzuki Hayabusa remains firmly in place as motorcycling’s Ultimate Sportbike. The 2024 version of Suzuki’s flagship sportbike continues to be propelled by a muscular, refined inline four-cylinder engine housed in a proven, yet modernized chassis with incomparable manners, managed by an unequaled suite of electronic rider aids within stunning aerodynamic bodywork that is distinctly Hayabusa.",
                            IsActive = true,
                            Price = 18999m,
                            Quantity = 20m,
                            Title = "SUZUKI HAYABUSA"
                        },
                        new
                        {
                            Id = 18,
                            Description = "An exotic blend of heritage, styling, and engineering—the refined 2024 Suzuki KATANA is poised to revolutionize your cherished motorcycle collection. Named after the legendary samurai sword, the KATANA retains its iconic design and features technical updates designed to enhance the riding pleasure of this distinctive motorcycle.",
                            IsActive = true,
                            Price = 13899m,
                            Quantity = 7m,
                            Title = "SUZUKI KATANA"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Ready to make a statement? Swing a leg over the 2024 Suzuki GSX-8S and let your riding speak volumes. Engineered from the ground up as an innovative path for future Suzuki sportbikes, the GSX-8S is a naked street fighter with a robust engine, an agile chassis, a suite of rider aids, plus stunning looks with a smart price that is a statement to your brilliance.",
                            IsActive = true,
                            Price = 8999m,
                            Quantity = 15m,
                            Title = "SUZUKI GSX-8S"
                        },
                        new
                        {
                            Id = 20,
                            Description = "The 2024 GSX-S1000GT intelligently combines the championship performance of its GSX-R1000-based engine with a nimble, lightweight chassis to provide riders with an exciting and comfortable GT riding experience.  Here is a Grand Tourer with sportbike level functionality, avantgarde styling, and an extensive selection of optional equipment like truly functional, integrated side cases.",
                            IsActive = true,
                            Price = 13499m,
                            Quantity = 15m,
                            Title = "SUZUKI GSX-S1000GT"
                        });
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsMainImage")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilePath = "/images/products/1/main.jpg",
                            IsMainImage = true,
                            ProductId = 1,
                            Title = "MT-10.main"
                        },
                        new
                        {
                            Id = 2,
                            FilePath = "/images/products/1/1.jpg",
                            IsMainImage = false,
                            ProductId = 1,
                            Title = "MT-10.01"
                        },
                        new
                        {
                            Id = 3,
                            FilePath = "/images/products/1/2.jpg",
                            IsMainImage = false,
                            ProductId = 1,
                            Title = "MT-10.02"
                        },
                        new
                        {
                            Id = 4,
                            FilePath = "/images/products/1/3.jpg",
                            IsMainImage = false,
                            ProductId = 1,
                            Title = "MT-10.03"
                        },
                        new
                        {
                            Id = 5,
                            FilePath = "/images/products/2/main.jpg",
                            IsMainImage = true,
                            ProductId = 2,
                            Title = "TRACER 9.main"
                        },
                        new
                        {
                            Id = 6,
                            FilePath = "/images/products/2/1.jpg",
                            IsMainImage = false,
                            ProductId = 2,
                            Title = "TRACER 9.01"
                        },
                        new
                        {
                            Id = 7,
                            FilePath = "/images/products/2/2.jpg",
                            IsMainImage = false,
                            ProductId = 2,
                            Title = "TRACER 9.02"
                        },
                        new
                        {
                            Id = 8,
                            FilePath = "/images/products/2/3.jpg",
                            IsMainImage = false,
                            ProductId = 2,
                            Title = "TRACER 9.03"
                        },
                        new
                        {
                            Id = 9,
                            FilePath = "/images/products/3/main.jpg",
                            IsMainImage = true,
                            ProductId = 3,
                            Title = "R1.main"
                        },
                        new
                        {
                            Id = 10,
                            FilePath = "/images/products/3/1.jpg",
                            IsMainImage = false,
                            ProductId = 3,
                            Title = "R1.01"
                        },
                        new
                        {
                            Id = 11,
                            FilePath = "/images/products/3/2.jpg",
                            IsMainImage = false,
                            ProductId = 3,
                            Title = "R1.02"
                        },
                        new
                        {
                            Id = 12,
                            FilePath = "/images/products/3/3.jpg",
                            IsMainImage = false,
                            ProductId = 3,
                            Title = "R1.03"
                        },
                        new
                        {
                            Id = 13,
                            FilePath = "/images/products/4/main.jpg",
                            IsMainImage = true,
                            ProductId = 4,
                            Title = "XSR900.main"
                        },
                        new
                        {
                            Id = 14,
                            FilePath = "/images/products/4/1.jpg",
                            IsMainImage = false,
                            ProductId = 4,
                            Title = "XSR900.01"
                        },
                        new
                        {
                            Id = 15,
                            FilePath = "/images/products/4/2.jpg",
                            IsMainImage = false,
                            ProductId = 4,
                            Title = "XSR900.02"
                        },
                        new
                        {
                            Id = 16,
                            FilePath = "/images/products/4/3.jpg",
                            IsMainImage = false,
                            ProductId = 4,
                            Title = "XSR900.03"
                        },
                        new
                        {
                            Id = 17,
                            FilePath = "/images/products/5/main.jpg",
                            IsMainImage = true,
                            ProductId = 5,
                            Title = "NIKEN.main"
                        },
                        new
                        {
                            Id = 18,
                            FilePath = "/images/products/5/1.jpg",
                            IsMainImage = false,
                            ProductId = 5,
                            Title = "NIKEN.01"
                        },
                        new
                        {
                            Id = 19,
                            FilePath = "/images/products/5/2.jpg",
                            IsMainImage = false,
                            ProductId = 5,
                            Title = "NIKEN.02"
                        },
                        new
                        {
                            Id = 20,
                            FilePath = "/images/products/5/3.jpg",
                            IsMainImage = false,
                            ProductId = 5,
                            Title = "NIKEN.03"
                        },
                        new
                        {
                            Id = 21,
                            FilePath = "/images/products/6/main.jpg",
                            IsMainImage = true,
                            ProductId = 6,
                            Title = "CB1000R.main"
                        },
                        new
                        {
                            Id = 22,
                            FilePath = "/images/products/6/1.jpg",
                            IsMainImage = false,
                            ProductId = 6,
                            Title = "CB1000R.01"
                        },
                        new
                        {
                            Id = 23,
                            FilePath = "/images/products/6/2.jpg",
                            IsMainImage = false,
                            ProductId = 6,
                            Title = "CB1000R.02"
                        },
                        new
                        {
                            Id = 24,
                            FilePath = "/images/products/6/3.jpg",
                            IsMainImage = false,
                            ProductId = 6,
                            Title = "CB1000R.03"
                        },
                        new
                        {
                            Id = 25,
                            FilePath = "/images/products/7/main.jpg",
                            IsMainImage = true,
                            ProductId = 7,
                            Title = "CB1000RR.main"
                        },
                        new
                        {
                            Id = 26,
                            FilePath = "/images/products/7/1.jpg",
                            IsMainImage = false,
                            ProductId = 7,
                            Title = "CB1000RR.01"
                        },
                        new
                        {
                            Id = 27,
                            FilePath = "/images/products/7/2.jpg",
                            IsMainImage = false,
                            ProductId = 7,
                            Title = "CB1000RR.02"
                        },
                        new
                        {
                            Id = 28,
                            FilePath = "/images/products/7/3.jpg",
                            IsMainImage = false,
                            ProductId = 7,
                            Title = "CB1000RR.03"
                        },
                        new
                        {
                            Id = 29,
                            FilePath = "/images/products/8/main.jpg",
                            IsMainImage = true,
                            ProductId = 8,
                            Title = "CB750.main"
                        },
                        new
                        {
                            Id = 30,
                            FilePath = "/images/products/8/1.jpg",
                            IsMainImage = false,
                            ProductId = 8,
                            Title = "CB750.01"
                        },
                        new
                        {
                            Id = 31,
                            FilePath = "/images/products/8/2.jpg",
                            IsMainImage = false,
                            ProductId = 8,
                            Title = "CB750.02"
                        },
                        new
                        {
                            Id = 32,
                            FilePath = "/images/products/8/3.jpg",
                            IsMainImage = false,
                            ProductId = 8,
                            Title = "CB750.03"
                        },
                        new
                        {
                            Id = 33,
                            FilePath = "/images/products/9/main.jpg",
                            IsMainImage = true,
                            ProductId = 9,
                            Title = "GL1800.main"
                        },
                        new
                        {
                            Id = 34,
                            FilePath = "/images/products/9/1.jpg",
                            IsMainImage = false,
                            ProductId = 9,
                            Title = "GL1800.01"
                        },
                        new
                        {
                            Id = 35,
                            FilePath = "/images/products/9/2.jpg",
                            IsMainImage = false,
                            ProductId = 9,
                            Title = "GL1800.02"
                        },
                        new
                        {
                            Id = 36,
                            FilePath = "/images/products/9/3.jpg",
                            IsMainImage = false,
                            ProductId = 9,
                            Title = "GL1800.03"
                        },
                        new
                        {
                            Id = 37,
                            FilePath = "/images/products/10/main.jpg",
                            IsMainImage = true,
                            ProductId = 10,
                            Title = "NT1100.main"
                        },
                        new
                        {
                            Id = 38,
                            FilePath = "/images/products/10/1.jpg",
                            IsMainImage = false,
                            ProductId = 10,
                            Title = "NT1100.01"
                        },
                        new
                        {
                            Id = 39,
                            FilePath = "/images/products/10/2.jpg",
                            IsMainImage = false,
                            ProductId = 10,
                            Title = "NT1100.02"
                        },
                        new
                        {
                            Id = 40,
                            FilePath = "/images/products/10/3.jpg",
                            IsMainImage = false,
                            ProductId = 10,
                            Title = "NT1100.03"
                        },
                        new
                        {
                            Id = 41,
                            FilePath = "/images/products/11/main.jpg",
                            IsMainImage = true,
                            ProductId = 11,
                            Title = "VULCAN 900.main"
                        },
                        new
                        {
                            Id = 42,
                            FilePath = "/images/products/11/1.jpg",
                            IsMainImage = false,
                            ProductId = 11,
                            Title = "VULCAN 900.01"
                        },
                        new
                        {
                            Id = 43,
                            FilePath = "/images/products/11/2.jpg",
                            IsMainImage = false,
                            ProductId = 11,
                            Title = "VULCAN 900.02"
                        },
                        new
                        {
                            Id = 44,
                            FilePath = "/images/products/11/3.jpg",
                            IsMainImage = false,
                            ProductId = 11,
                            Title = "VULCAN 900.03"
                        },
                        new
                        {
                            Id = 45,
                            FilePath = "/images/products/12/main.jpg",
                            IsMainImage = true,
                            ProductId = 12,
                            Title = "NINJA 1000SX.main"
                        },
                        new
                        {
                            Id = 46,
                            FilePath = "/images/products/12/1.jpg",
                            IsMainImage = false,
                            ProductId = 12,
                            Title = "NINJA 1000SX.01"
                        },
                        new
                        {
                            Id = 47,
                            FilePath = "/images/products/12/2.jpg",
                            IsMainImage = false,
                            ProductId = 12,
                            Title = "NINJA 1000SX.02"
                        },
                        new
                        {
                            Id = 48,
                            FilePath = "/images/products/12/3.jpg",
                            IsMainImage = false,
                            ProductId = 12,
                            Title = "NINJA 1000SX.03"
                        },
                        new
                        {
                            Id = 49,
                            FilePath = "/images/products/13/main.jpg",
                            IsMainImage = true,
                            ProductId = 13,
                            Title = "NINJA ZX-10R.main"
                        },
                        new
                        {
                            Id = 50,
                            FilePath = "/images/products/13/1.jpg",
                            IsMainImage = false,
                            ProductId = 13,
                            Title = "NINJA ZX-10R.01"
                        },
                        new
                        {
                            Id = 51,
                            FilePath = "/images/products/13/2.jpg",
                            IsMainImage = false,
                            ProductId = 13,
                            Title = "NINJA ZX-10R.02"
                        },
                        new
                        {
                            Id = 52,
                            FilePath = "/images/products/13/3.jpg",
                            IsMainImage = false,
                            ProductId = 13,
                            Title = "NINJA ZX-10R.03"
                        },
                        new
                        {
                            Id = 53,
                            FilePath = "/images/products/14/main.jpg",
                            IsMainImage = true,
                            ProductId = 14,
                            Title = "Z900.main"
                        },
                        new
                        {
                            Id = 54,
                            FilePath = "/images/products/14/1.jpg",
                            IsMainImage = false,
                            ProductId = 14,
                            Title = "Z900.01"
                        },
                        new
                        {
                            Id = 55,
                            FilePath = "/images/products/14/2.jpg",
                            IsMainImage = false,
                            ProductId = 14,
                            Title = "Z900.02"
                        },
                        new
                        {
                            Id = 56,
                            FilePath = "/images/products/14/3.jpg",
                            IsMainImage = false,
                            ProductId = 14,
                            Title = "Z900.03"
                        },
                        new
                        {
                            Id = 57,
                            FilePath = "/images/products/15/main.jpg",
                            IsMainImage = true,
                            ProductId = 15,
                            Title = "NINJA H2R.main"
                        },
                        new
                        {
                            Id = 58,
                            FilePath = "/images/products/15/1.jpg",
                            IsMainImage = false,
                            ProductId = 15,
                            Title = "NINJA H2R.01"
                        },
                        new
                        {
                            Id = 59,
                            FilePath = "/images/products/15/2.jpg",
                            IsMainImage = false,
                            ProductId = 15,
                            Title = "NINJA H2R.02"
                        },
                        new
                        {
                            Id = 60,
                            FilePath = "/images/products/15/3.jpg",
                            IsMainImage = false,
                            ProductId = 15,
                            Title = "NINJA H2R.03"
                        },
                        new
                        {
                            Id = 61,
                            FilePath = "/images/products/16/main.jpg",
                            IsMainImage = true,
                            ProductId = 16,
                            Title = "GSX-R1000R.main"
                        },
                        new
                        {
                            Id = 62,
                            FilePath = "/images/products/16/1.jpg",
                            IsMainImage = false,
                            ProductId = 16,
                            Title = "GSX-R1000R.01"
                        },
                        new
                        {
                            Id = 63,
                            FilePath = "/images/products/16/2.jpg",
                            IsMainImage = false,
                            ProductId = 16,
                            Title = "GSX-R1000R.02"
                        },
                        new
                        {
                            Id = 64,
                            FilePath = "/images/products/16/3.jpg",
                            IsMainImage = false,
                            ProductId = 16,
                            Title = "GSX-R1000R.03"
                        },
                        new
                        {
                            Id = 65,
                            FilePath = "/images/products/17/main.jpg",
                            IsMainImage = true,
                            ProductId = 17,
                            Title = "HAYABUSA.main"
                        },
                        new
                        {
                            Id = 66,
                            FilePath = "/images/products/17/1.jpg",
                            IsMainImage = false,
                            ProductId = 17,
                            Title = "HAYABUSA.01"
                        },
                        new
                        {
                            Id = 67,
                            FilePath = "/images/products/17/2.jpg",
                            IsMainImage = false,
                            ProductId = 17,
                            Title = "HAYABUSA.02"
                        },
                        new
                        {
                            Id = 68,
                            FilePath = "/images/products/17/3.jpg",
                            IsMainImage = false,
                            ProductId = 17,
                            Title = "HAYABUSA.03"
                        },
                        new
                        {
                            Id = 69,
                            FilePath = "/images/products/18/main.jpg",
                            IsMainImage = true,
                            ProductId = 18,
                            Title = "KATANA.main"
                        },
                        new
                        {
                            Id = 70,
                            FilePath = "/images/products/18/1.jpg",
                            IsMainImage = false,
                            ProductId = 18,
                            Title = "KATANA.01"
                        },
                        new
                        {
                            Id = 71,
                            FilePath = "/images/products/18/2.jpg",
                            IsMainImage = false,
                            ProductId = 18,
                            Title = "KATANA.02"
                        },
                        new
                        {
                            Id = 72,
                            FilePath = "/images/products/18/3.jpg",
                            IsMainImage = false,
                            ProductId = 18,
                            Title = "KATANA.03"
                        },
                        new
                        {
                            Id = 73,
                            FilePath = "/images/products/19/main.jpg",
                            IsMainImage = true,
                            ProductId = 19,
                            Title = "GSX-8S.main"
                        },
                        new
                        {
                            Id = 74,
                            FilePath = "/images/products/19/1.jpg",
                            IsMainImage = false,
                            ProductId = 19,
                            Title = "GSX-8S.01"
                        },
                        new
                        {
                            Id = 75,
                            FilePath = "/images/products/19/2.jpg",
                            IsMainImage = false,
                            ProductId = 19,
                            Title = "GSX-8S.02"
                        },
                        new
                        {
                            Id = 76,
                            FilePath = "/images/products/19/3.jpg",
                            IsMainImage = false,
                            ProductId = 19,
                            Title = "GSX-8S.03"
                        },
                        new
                        {
                            Id = 77,
                            FilePath = "/images/products/20/main.jpg",
                            IsMainImage = true,
                            ProductId = 20,
                            Title = "GSX-S1000GT.main"
                        },
                        new
                        {
                            Id = 78,
                            FilePath = "/images/products/20/1.jpg",
                            IsMainImage = false,
                            ProductId = 20,
                            Title = "GSX-S1000GT.01"
                        },
                        new
                        {
                            Id = 79,
                            FilePath = "/images/products/20/2.jpg",
                            IsMainImage = false,
                            ProductId = 20,
                            Title = "GSX-S1000GT.02"
                        },
                        new
                        {
                            Id = 80,
                            FilePath = "/images/products/20/3.jpg",
                            IsMainImage = false,
                            ProductId = 20,
                            Title = "GSX-S1000GT.03"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Motorcycle_WebShop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Motorcycle_WebShop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motorcycle_WebShop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Motorcycle_WebShop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.Order", b =>
                {
                    b.HasOne("Motorcycle_WebShop.Data.ApplicationUser", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.OrderItem", b =>
                {
                    b.HasOne("Motorcycle_WebShop.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motorcycle_WebShop.Models.Product", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.ProductCategory", b =>
                {
                    b.HasOne("Motorcycle_WebShop.Models.Category", null)
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motorcycle_WebShop.Models.Product", null)
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.ProductImage", b =>
                {
                    b.HasOne("Motorcycle_WebShop.Models.Product", null)
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Motorcycle_WebShop.Data.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Motorcycle_WebShop.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
